version: '3'

services:
  http-server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    environment:
      - PORT=:8080

  http-client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    environment:
      - HOST=http://http-server
      - API_ENDPOINT=/network
      - PORT=:8080
      - INTERVAL=5s
      - INTERFACE=